// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'RUNE Interface',
      items: [
        'rune-interface/getting-started',
        'rune-interface/localization',
        'rune-interface/mcp-server',
      ],
    },
    {
      type: 'category',
      label: 'RUNE CLI',
      items: [
        'rune-cli/getting-started',
      ],
    },
    {
      type: 'category',
      label: 'Luau API',
      items: [
        {
          type: 'category',
          label: 'Core Systems',
          items: [
            'luau/session-state',
            'luau/flow-file',
            'luau/logger',
            'luau/workflow',
            'luau/commandline',
            'luau/http',
            'luau/yaml',
            'luau/ini',
            'luau/csv',
            'luau/json',
            'luau/environment',
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [
            'luau/functions/session-state-set',
            'luau/functions/session-state-get',
            'luau/functions/session-state-del',
            'luau/functions/session-state-has',
            'luau/functions/session-state-contains',
            'luau/functions/flow-file-read',
            'luau/functions/flow-file-write',
            'luau/functions/flow-file-exists',
            'luau/functions/flow-file-list',
            'luau/functions/logger-info',
            'luau/functions/logger-warn',
            'luau/functions/logger-error',
            'luau/functions/logger-debug',
            'luau/functions/trigger-workflow',
            'luau/functions/execute-command',
            'luau/functions/http-request',
            'luau/functions/parse-yaml-string',
            'luau/functions/parse-yaml-file',
            'luau/functions/parse-ini-string',
            'luau/functions/parse-ini-file',
            'luau/functions/parse-csv-string',
            'luau/functions/parse-csv-file',
            'luau/functions/parse-json-string',
            'luau/functions/parse-json-file',
            'luau/functions/get-env',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Nodes',
      items: [
        {
          type: 'category',
          label: 'Flow Control',
          items: [
            'nodes/branch',
            'nodes/sequence',
            'nodes/foreach',
            'nodes/do-n',
            'nodes/trigger-flow',
            'nodes/success',
            'nodes/failed',
          ],
        },
        {
          type: 'category',
          label: 'Events',
          items: [
            'nodes/button-event',
            'nodes/cron-event',
          ],
        },
        {
          type: 'category',
          label: 'Session State',
          items: [
            'nodes/session-state-set',
            'nodes/session-state-get',
            'nodes/session-state-del',
          ],
        },
        {
          type: 'category',
          label: 'Data Types',
          items: [
            'nodes/text',
            'nodes/integer',
            'nodes/float',
            'nodes/boolean',
          ],
        },
        {
          type: 'category',
          label: 'Math Operations',
          items: [
            'nodes/math-add',
            'nodes/math-sub',
            'nodes/math-mul',
            'nodes/math-div',
            'nodes/math-mod',
            'nodes/math-abs-integer',
            'nodes/math-abs-float',
            'nodes/math-sqrt',
            'nodes/math-pow',
            'nodes/math-ceil',
            'nodes/math-floor',
            'nodes/math-round',
            'nodes/math-round-float',
            'nodes/math-round-integer',
            'nodes/math-log',
            'nodes/math-log10',
            'nodes/math-exp',
            'nodes/math-fmod',
            'nodes/math-hypot',
            'nodes/math-max-integer',
            'nodes/math-min-integer',
            'nodes/math-max-float',
            'nodes/math-min-float',
          ],
        },
        {
          type: 'category',
          label: 'String Operations',
          items: [
            'nodes/string-concat',
            'nodes/string-left',
            'nodes/string-right',
            'nodes/string-substring',
            'nodes/string-specific-char',
          ],
        },
        {
          type: 'category',
          label: 'Type Conversions',
          items: [
            'nodes/string-to-integer',
            'nodes/integer-to-string',
            'nodes/string-to-float',
            'nodes/float-to-string',
            'nodes/string-to-boolean',
            'nodes/boolean-to-string',
            'nodes/integer-to-float',
            'nodes/float-to-integer',
          ],
        },
        {
          type: 'category',
          label: 'Comparisons',
          items: [
            'nodes/string-compare',
            'nodes/number-compare',
            'nodes/boolean-compare',
            'nodes/array-compare',
            'nodes/object-compare',
            'nodes/date-time-compare-unix',
            'nodes/date-time-compare-iso',
          ],
        },
        {
          type: 'category',
          label: 'File Operations',
          items: [
            'nodes/load-text-file',
            'nodes/save-to-text-file',
            'nodes/load-json-file',
            'nodes/save-to-json-file',
            'nodes/file-exists',
          ],
        },
        {
          type: 'category',
          label: 'JSON Operations',
          items: [
            'nodes/load-json-string',
            'nodes/text-to-json',
            'nodes/is-text-valid-json',
            'nodes/loop-json-array',
            'nodes/loop-json-object',
            'nodes/json-to-string',
          ],
        },
        {
          type: 'category',
          label: 'YAML Operations',
          items: [
            'nodes/load-yaml-string',
            'nodes/load-yaml-file',
            'nodes/loop-yaml-array',
            'nodes/string-to-yaml',
            'nodes/yaml-to-string',
          ],
        },
        {
          type: 'category',
          label: 'INI Operations',
          items: [
            'nodes/load-ini-string',
            'nodes/load-ini-file',
            'nodes/loop-ini-categories',
            'nodes/loop-ini-key-value',
            'nodes/string-to-ini',
            'nodes/ini-to-string',
          ],
        },
        {
          type: 'category',
          label: 'CSV Operations',
          items: [
            'nodes/load-csv-string',
            'nodes/load-csv-file',
            'nodes/loop-csv-entries',
            'nodes/string-to-csv',
            'nodes/csv-to-string',
          ],
        },
        {
          type: 'category',
          label: 'Crypto',
          items: [
            'nodes/crypto-generate-random',
            'nodes/crypto-hash',
            'nodes/crypto-hmac',
            'nodes/crypto-sign',
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          items: [
            'nodes/console',
            'nodes/commandline',
            'nodes/get-environment-variable',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
